#!/usr/bin/env bash
set -euo pipefail
if [[ -n "${DEBUG:-}" ]]; then
  set -x
fi
IFS=$'\n\t'
readonly DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))

OS=`uname -s`
if [ "${OS}" = "Darwin" ]; then
  # brew bundle --file=${DIR}/Brewfile
  true
fi

npm install -g @google-cloud/functions-emulator
npm install -g serverless